{
 "title": "uuid-app",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "UUID-app Total replicas",
   "type": "stat",
   "description": "UUID-app custom metrics\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"uuid-app\",namespace=\"uuid-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UUID-app replicas ready",
   "type": "stat",
   "description": "UUID-app custom metrics\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"uuid-app\",namespace=\"uuid-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UUID-app Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_get_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET requests served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_get_requests_total{namespace=\"uuid-app\",app=\"uuid-app\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}